//! `pending_queries` persistence (T095/T096/T097/T099/I3). The proactive-query
//! lifecycle row: generated by I3 detection (T095), answered/skipped (T096),
//! auto-expired (T097), and listed by the Pending DecisionCard (T099).
//!
//! Multi-table transitions that also touch `im_messages` / `mails` / `ai_drafts`
//! live in `ai::pipeline::i3_stage` and the resume/expiry stages; this module
//! owns only the `pending_queries` table.

use sqlx::Row;

use super::{map_sqlx_err, Db};
use crate::error::{AppError, AppResult};
use crate::types::PendingQuery;
use crate::util::{new_uuid, now_unix};

/// 72 hours — the non-T4 expiry window (F_I3 §4.2).
pub const QUERY_TTL_SECS: i64 = 72 * 3600;
/// Anti-over-notify daily cap per account (F_I3 §6).
pub const DAILY_CARD_CAP: i64 = 10;
/// Dedup window for repeat queries from the same sender (F_I3 §6).
pub const DEDUP_WINDOW_SECS: i64 = 48 * 3600;

const COLS: &str = "id, account_id, mail_id, risk_event_id, trigger_type, question, options, \
     answer, status, priority, expires_at, answered_at, created_at";

/// Resolved fields for a new `pending_queries` row (built by I3, T095).
#[derive(Debug, Clone)]
pub struct NewQuery {
    pub account_id: String,
    pub mail_id: Option<String>,
    pub risk_event_id: Option<String>,
    pub trigger_type: String,
    pub question: String,
    pub options: Option<String>,
    pub priority: i64,
    /// `None` for T4 (never expires).
    pub expires_at: Option<i64>,
}

fn row_to_query(row: &sqlx::sqlite::SqliteRow) -> PendingQuery {
    PendingQuery {
        id: row.get("id"),
        account_id: row.get("account_id"),
        mail_id: row.get("mail_id"),
        risk_event_id: row.get("risk_event_id"),
        trigger_type: row.get("trigger_type"),
        question: row.get("question"),
        options: row.get("options"),
        answer: row.get("answer"),
        status: row.get("status"),
        priority: row.get("priority"),
        expires_at: row.get("expires_at"),
        answered_at: row.get("answered_at"),
        created_at: row.get("created_at"),
    }
}

/// Insert one query row and return it (T095).
pub async fn insert_query(db: &Db, q: &NewQuery) -> AppResult<PendingQuery> {
    let id = new_uuid();
    let now = now_unix();
    sqlx::query(
        "INSERT INTO pending_queries (id, account_id, mail_id, risk_event_id, trigger_type, \
             question, options, status, priority, expires_at, created_at) \
         VALUES (?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?, ?)",
    )
    .bind(&id)
    .bind(&q.account_id)
    .bind(&q.mail_id)
    .bind(&q.risk_event_id)
    .bind(&q.trigger_type)
    .bind(&q.question)
    .bind(&q.options)
    .bind(q.priority)
    .bind(q.expires_at)
    .bind(now)
    .execute(db.pool())
    .await
    .map_err(map_sqlx_err)?;
    get_query(db, &id).await
}

/// Replace the `options` JSON (T098 stores the full QA card content here so the
/// Pending DecisionCard is self-contained from `list_pending_queries`).
pub async fn set_options(db: &Db, id: &str, options_json: &str) -> AppResult<()> {
    sqlx::query("UPDATE pending_queries SET options = ? WHERE id = ?")
        .bind(options_json)
        .bind(id)
        .execute(db.pool())
        .await
        .map_err(map_sqlx_err)?;
    Ok(())
}

/// One query by id (`NOT_FOUND` if absent).
pub async fn get_query(db: &Db, id: &str) -> AppResult<PendingQuery> {
    let sql = format!("SELECT {COLS} FROM pending_queries WHERE id = ?");
    let row = sqlx::query(&sql)
        .bind(id)
        .fetch_optional(db.pool())
        .await
        .map_err(map_sqlx_err)?
        .ok_or(AppError::NotFound)?;
    Ok(row_to_query(&row))
}

/// Pending queries, highest-priority first, optionally scoped to one account
/// (T099 `list_pending_queries`).
pub async fn list_pending(db: &Db, account_id: Option<&str>) -> AppResult<Vec<PendingQuery>> {
    let rows = if let Some(acc) = account_id {
        let sql = format!(
            "SELECT {COLS} FROM pending_queries WHERE status = 'pending' AND account_id = ? \
             ORDER BY priority ASC, created_at ASC"
        );
        sqlx::query(&sql).bind(acc).fetch_all(db.pool()).await
    } else {
        let sql = format!(
            "SELECT {COLS} FROM pending_queries WHERE status = 'pending' \
             ORDER BY priority ASC, created_at ASC"
        );
        sqlx::query(&sql).fetch_all(db.pool()).await
    }
    .map_err(map_sqlx_err)?;
    Ok(rows.iter().map(row_to_query).collect())
}

/// Number of queries still awaiting a human answer (T101 sidebar badge).
pub async fn count_pending(db: &Db) -> AppResult<i64> {
    let (n,): (i64,) =
        sqlx::query_as("SELECT count(*) FROM pending_queries WHERE status = 'pending'")
            .fetch_one(db.pool())
            .await
            .map_err(map_sqlx_err)?;
    Ok(n)
}

/// Cards created for an account in the last 24 h — the anti-over-notify guard
/// (F_I3 §6). T4 is excluded from the cap (risk alerts must never be suppressed).
pub async fn daily_count(db: &Db, account_id: &str) -> AppResult<i64> {
    let since = now_unix() - 86_400;
    let (n,): (i64,) = sqlx::query_as(
        "SELECT count(*) FROM pending_queries \
         WHERE account_id = ? AND trigger_type != 'T4' AND created_at > ?",
    )
    .bind(account_id)
    .bind(since)
    .fetch_one(db.pool())
    .await
    .map_err(map_sqlx_err)?;
    Ok(n)
}

/// Whether the same sender already raised a query within the dedup window
/// (F_I3 §6). Joins `mails` to compare the sender address.
pub async fn sender_has_recent_query(
    db: &Db,
    account_id: &str,
    from_email: &str,
    trigger_type: &str,
) -> AppResult<bool> {
    let since = now_unix() - DEDUP_WINDOW_SECS;
    let (n,): (i64,) = sqlx::query_as(
        "SELECT count(*) FROM pending_queries pq \
         JOIN mails m ON m.id = pq.mail_id \
         WHERE pq.account_id = ? AND pq.trigger_type = ? AND m.from_email = ? \
           AND pq.created_at > ?",
    )
    .bind(account_id)
    .bind(trigger_type)
    .bind(from_email)
    .bind(since)
    .fetch_one(db.pool())
    .await
    .map_err(map_sqlx_err)?;
    Ok(n > 0)
}

/// Whether a mail already has a non-terminal query (avoid two cards per mail).
pub async fn mail_has_active_query(db: &Db, mail_id: &str) -> AppResult<bool> {
    let (n,): (i64,) = sqlx::query_as(
        "SELECT count(*) FROM pending_queries \
         WHERE mail_id = ? AND status IN ('pending', 'answered')",
    )
    .bind(mail_id)
    .fetch_one(db.pool())
    .await
    .map_err(map_sqlx_err)?;
    Ok(n > 0)
}

#[cfg(test)]
mod tests {
    use super::*;

    async fn db_with_account() -> Db {
        let db = Db::connect_in_memory().await.unwrap();
        db.run_migrations().await.unwrap();
        sqlx::query(
            "INSERT INTO accounts (id, email, display_name, provider, color_token, badge_label, \
                 created_at, updated_at) VALUES ('a','a@x.com','A','imap','slate','A',0,0)",
        )
        .execute(db.pool())
        .await
        .unwrap();
        db
    }

    fn new_q(trigger: &str, mail_id: Option<&str>, priority: i64) -> NewQuery {
        NewQuery {
            account_id: "a".into(),
            mail_id: mail_id.map(String::from),
            risk_event_id: None,
            trigger_type: trigger.into(),
            question: "Who is this sender?".into(),
            options: Some("[\"Yes\",\"No\"]".into()),
            priority,
            expires_at: Some(now_unix() + QUERY_TTL_SECS),
        }
    }

    #[tokio::test]
    async fn insert_get_list_count() {
        let db = db_with_account().await;
        let q = insert_query(&db, &new_q("T1", None, 3)).await.unwrap();
        assert_eq!(q.status, "pending");
        assert_eq!(get_query(&db, &q.id).await.unwrap().id, q.id);

        insert_query(&db, &new_q("T4", None, 1)).await.unwrap();
        let pending = list_pending(&db, None).await.unwrap();
        // T4 (priority 1) sorts ahead of T1 (priority 3).
        assert_eq!(pending.len(), 2);
        assert_eq!(pending[0].trigger_type, "T4");
        assert_eq!(count_pending(&db).await.unwrap(), 2);
    }

    #[tokio::test]
    async fn daily_count_excludes_t4() {
        let db = db_with_account().await;
        insert_query(&db, &new_q("T1", None, 3)).await.unwrap();
        insert_query(&db, &new_q("T2", None, 3)).await.unwrap();
        insert_query(&db, &new_q("T4", None, 1)).await.unwrap();
        // T4 excluded from the daily cap count.
        assert_eq!(daily_count(&db, "a").await.unwrap(), 2);
    }

    #[tokio::test]
    async fn sender_dedup_detects_recent_same_sender() {
        let db = db_with_account().await;
        let now = now_unix();
        sqlx::query(
            "INSERT INTO mails (id, account_id, message_id, from_email, to_addrs, date_sent, \
                 date_received, created_at, updated_at) \
             VALUES ('m1','a','<m1>','bob@x.com','[]', ?, ?, ?, ?)",
        )
        .bind(now)
        .bind(now)
        .bind(now)
        .bind(now)
        .execute(db.pool())
        .await
        .unwrap();
        insert_query(&db, &new_q("T1", Some("m1"), 3))
            .await
            .unwrap();
        assert!(sender_has_recent_query(&db, "a", "bob@x.com", "T1")
            .await
            .unwrap());
        assert!(!sender_has_recent_query(&db, "a", "carol@x.com", "T1")
            .await
            .unwrap());
    }
}
