#!/usr/bin/env bash
# Generate THIRD-PARTY-NOTICES.md (full per-dependency license texts) for a release.
#
# Prerequisites (install once):
#   cargo install cargo-about --locked --features cli
#   pnpm install --frozen-lockfile
#
# Run from the repo root:
#   bash scripts/ci/generate-notice.sh
set -euo pipefail
cd "$(dirname "$0")/../.."

OUT="THIRD-PARTY-NOTICES.md"

{
  echo "# Third-Party Notices - SeekerMail Desktop"
  echo
  echo "Generated by \`scripts/ci/generate-notice.sh\`. SeekerMail Desktop is licensed under"
  echo "AGPL-3.0-only (see LICENSE); a separate commercial license is available (see LICENSING.md)."
  echo "The components below are bundled under their own licenses and are NOT modified by SeekerMail."
  echo
} > "$OUT"

# --- Rust (the shipped desktop application = src-tauri) ---
echo "Generating Rust notices via cargo-about ..."
cargo about generate --manifest-path src-tauri/Cargo.toml about.hbs >> "$OUT"

# --- JavaScript / npm (the frontend) ---
echo "Generating npm notices ..."
echo >> "$OUT"
node scripts/ci/generate-notice.mjs >> "$OUT"

echo "Wrote $OUT"
