// @generated by `pnpm gen:types` from Rust types (specta). DO NOT EDIT.
// Source of truth: src-tauri/src/types.rs and src-tauri/src/error.rs (T003).
/**
 * An email account / digital-employee identity (01 `accounts`). Credential-free
 * by construction — secrets live only in the Keychain (T006).
 */
export type Account = { id: string; email: string; displayName: string; provider: string; imapHost: string | null; imapPort: number; smtpHost: string | null; smtpPort: number; colorToken: string; badgeLabel: string; roleType: string; roleDescription: string | null; authLevel: number; isPrimary: boolean; isActive: boolean; syncIntervalSecs: number; lastSyncedAt: number | null; 
/**
 * `None` = "all mail"; `Some(n)` = last `n` months (T016).
 */
knowledgeDepthMonths: number | null; createdAt: number; updatedAt: number }

/**
 * Per-account AI configuration (`account_ai_settings`, 01) as seen by the
 * frontend (02 §1 `AccountAiSettings`).
 */
export type AccountAiSettings = { accountId: string; 
/**
 * 1 = Manual Only, 2 = Semi-Auto, 3 = Full Auto.
 */
authLevel: number; aiProvider: AiProvider; aiModel: string | null; aiBaseUrl: string | null; t1Enabled: boolean; t2Enabled: boolean; t3Enabled: boolean; t4Enabled: boolean; t5Enabled: boolean; t6Enabled: boolean; dailyQueryLimit: number; e3WhitelistOnly: boolean; e3MinHistory: number; styleSamplesCount: number; updatedAt: number }

/**
 * Derived Agent presence for one account (T094, F_I2 §4.2). Not persisted — it is
 * computed from `sync_state` + recent `ai_drafts`: `offline` when the account's
 * last sync failed auth/network, `processing` when a draft was generated in the
 * last 5 minutes, otherwise `idle`.
 */
export type AgentStatus = { accountId: string; 
/**
 * `processing` | `idle` | `offline`.
 */
status: string }

/**
 * One aggregated `ai_decisions` bucket for the 24h summary — counts and token
 * totals only, never content (09 §5).
 */
export type AiActivityRow = { accountId: string; 
/**
 * `ai_decisions.decision_type` (capability slug / decision tag).
 */
decisionType: string; 
/**
 * Model slug, or the `downgraded:*` placeholder for degraded calls.
 */
aiModel: string | null; requestCount: number; inputTokens: number; outputTokens: number }

/**
 * Output format for `export_ai_decisions` (F_E7 §4.7).
 */
export type AiDecisionExportFormat = "csv" | "json"

/**
 * One `ai_decisions` row as the UI consumes it (F_E7 §4.4): the full audit
 * record plus the trigger mail's subject (LEFT JOIN — subject only, never the
 * body) so the list can label each event.
 */
export type AiDecisionRow = { id: string; accountId: string; mailId: string | null; draftId: string | null; decisionType: string; 
/**
 * `risk` | `reply` | `identity` | `rule` | `context` (dev/01).
 */
impact: string; actionDescription: string; resultDescription: string; knowledgeRefs: string[]; knowledgeSummary: string | null; aiModel: string | null; inputTokens: number | null; outputTokens: number | null; latencyMs: number | null; createdAt: number; 
/**
 * Subject of the trigger mail, when it still exists (UI label only).
 */
mailSubject: string | null }

/**
 * One AI-generated reply draft (`ai_drafts`, dev/01). `body_original` is the
 * immutable AI output; `body_current` reflects user edits (E6).
 */
export type AiDraft = { id: string; triggerMailId: string; accountId: string; 
/**
 * Reply recipient — the trigger mail's sender.
 */
toAddr: Recipient; ccAddrs: Recipient[]; subject: string; bodyOriginal: string; bodyCurrent: string; isEdited: boolean; styleMatchScore: number | null; 
/**
 * `E1_manual` | `E2_semi` | `E3_auto`.
 */
triggerMode: string; aiModel: string; 
/**
 * Source mail ids of the GTE context used for generation (T074).
 */
knowledgeRefs: string[]; 
/**
 * `pending` | `edited` | `sent` | `discarded` | `expired`.
 */
status: string; sendAfter: number | null; expiresAt: number | null; sentAt: number | null; discardedAt: number | null; 
/**
 * `user` | `expired` | `superseded`.
 */
discardReason: string | null; createdAt: number; updatedAt: number }

/**
 * Where one account's AI requests terminate (the disclosure classification,
 * dev/06 §8): a cloud endpoint, a localhost daemon, an in-process model, or
 * nowhere because AI is off.
 */
export type AiEndpointKind = 
/**
 * Mail content leaves the device for this endpoint when AI runs.
 */
"cloud" | 
/**
 * A daemon on this device (e.g. Ollama on localhost) — content stays local.
 */
"local" | 
/**
 * The model runs inside the SeekerMail process — no endpoint at all.
 */
"in_process" | 
/**
 * AI is disabled for the account — nothing is sent anywhere.
 */
"none"

/**
 * `ai:offline` payload — every configured provider is cooled or unreachable.
 */
export type AiOfflinePayload = { reason: string }

/**
 * `ai:online` payload — a cooled provider passed its recovery probe.
 */
export type AiOnlinePayload = { recoveredProvider: string }

/**
 * Which AI backend serves an account (02 §1 `AiProvider`). Persisted in
 * `account_ai_settings.ai_provider` as the lowercase wire string. `None` means
 * AI is disabled for the account (E0); Gemini-style vendors ride the `openai`
 * variant with a custom `ai_base_url` (dev/06 §1).
 */
export type AiProvider = "openai" | "anthropic" | "ollama" | "local_onnx" | "none"

/**
 * One per-account AI routing row for the disclosure panel (card §3).
 */
export type AiRouteEntry = { accountId: string; accountEmail: string; 
/**
 * `accounts.color_token` — drives the account badge in the panel.
 */
colorToken: string; aiProvider: AiProvider; aiModel: string | null; endpointKind: AiEndpointKind; 
/**
 * The full effective endpoint URL (`ai_base_url` override or the
 * provider default). `None` for in-process and disabled rows.
 */
endpointUrl: string | null; 
/**
 * Display form — authority only (`api.openai.com`, `localhost:11434`),
 * no scheme or path (card §6: avoid over-technical URLs).
 */
endpointHost: string | null; 
/**
 * `true` for providers that never send mail content off this device
 * (`ollama`, `local_onnx`). Cloud rows carry the disclosure note.
 */
isLocal: boolean }

/**
 * Read-only status snapshot for the T069 status indicator panel (F_F5 §5).
 */
export type AiRouterStatus = { globalOffline: boolean; holdCount: number; cooldowns: CooldownInfo[] }

/**
 * Setup-state snapshot for the wizard + settings page: has the disclosure
 * been confirmed, is the conservative quota armed, when was first auth.
 */
export type AiSetupStatus = { disclosureConfirmedAt: number | null; conservativeQuotaUntil: number | null; firstAuthAt: number | null }

/**
 * Input to `analyze_legal_risk` (T070 §3).
 */
export type AnalyzeLegalRiskParams = { mailId: string; 
/**
 * `false` (the default) returns the cached analysis when one exists
 * within the last 24 hours — no provider call is made (F_D1 §4.5).
 */
forceNew?: boolean }

/**
 * Input to `analyze_sales_context` (T072 §3).
 */
export type AnalyzeSalesContextParams = { mailId: string; 
/**
 * `false` (the default) returns the cached analysis when one exists
 * within the last 24 hours — no provider call is made (T072 §3 step 1).
 */
forceNew?: boolean }

/**
 * Result of `approve_draft` (T090, E6 "Approve & Send"). `pendingId` feeds
 * the existing `cancel_send` command while the 10 s SMTP window is open.
 */
export type ApproveDraftResult = { sentAt: number; messageId: string; 
/**
 * Present when the send went through the queued path (undo window).
 */
pendingId: string | null }

/**
 * Attachment metadata row for the reading view (T025/T026).
 */
export type Attachment = { id: string; mailId: string; filename: string; contentType: string; sizeBytes: number; downloaded: boolean; localPath: string | null; isInline: boolean; contentId: string | null; checksumSha256: string | null }

/**
 * One attachment-origin search hit, enriched with its owning mail's metadata so
 * the search panel can render a full card without a second fetch (T110 §3a).
 */
export type AttachmentHit = { attachmentId: string; mailId: string; filename: string; contentType: string; 
/**
 * FTS5 `<mark>`-highlighted excerpt of the extracted text.
 */
excerpt: string; score: number; mailSubject: string; mailFromEmail: string; mailDateSent: number }

/**
 * Returned by `build_attachment_index` (T109): pending count + whether this call
 * started the build (`false` when one was already running).
 */
export type AttachmentIndexBuildStatus = { totalPending: number; started: boolean }

/**
 * `attachment_index:progress` — attachment vector-index heartbeat (T109).
 */
export type AttachmentIndexProgressPayload = { indexed: number; total: number; elapsedMs: number }

/**
 * `attachment:progress`.
 */
export type AttachmentProgressPayload = { attachmentId: string; pct: number }

/**
 * `attachment:ready`.
 */
export type AttachmentReadyPayload = { attachmentId: string; localPath: string }

/**
 * `auto:loop_detected` payload (T085) — the loop guard stopped a thread's
 * auto-replies (chain length reached the cap).
 */
export type AutoLoopDetectedPayload = { threadId: string; accountId: string }

/**
 * `auto:sent` payload (T085) — an E3 auto-reply left after its undo window.
 * Identifiers only; the frontend toast carries no mail content.
 */
export type AutoSentPayload = { draftId: string; accountId: string; messageId: string }

/**
 * History-backfill progress (T022, `backfill_state`).
 */
export type BackfillStatus = { accountId: string; status: string; depthMonths: number | null; boundaryDate: number | null; lastUidFetched: number | null; totalUidCount: number | null; fetchedCount: number; startedAt: number | null; pausedAt: number | null; completedAt: number | null; errorMessage: string | null; updatedAt: number }

/**
 * One item of a `batch_update_provider_matrix` call (T066 batch operations:
 * copy row / copy column / switch-all-E4-to-local, F_F4 §4.3).
 */
export type BatchMatrixUpdate = { accountId: string; capability: Capability; cell: MatrixCell }

/**
 * `begin_recommended_oauth` result: the state nonce the wizard must hand
 * back at completion, plus the URL that was opened in the system browser.
 */
export type BeginRecommendedOAuthResult = { state: string; authorizeUrl: string }

/**
 * `cancel_send` result (02 §3).
 */
export type CancelSendResult = { cancelled: boolean }

/**
 * What a generation/analysis call is *for*. Drives F4 capability×account
 * routing and the `ai_decisions` audit trail; never sent to the provider
 * (dev/06 §2.1).
 * 
 * Wire/JSON representation (T065 §6): the PascalCase variant name
 * (`"DraftReply"`, `"RiskReason"`, …) — this is what the persisted F4 matrix
 * and the specta-generated TypeScript union carry. [`Capability::as_str`]
 * stays snake_case for logs and `ai_decisions` rows.
 */
export type Capability = "DraftReply" | "RiskReason" | "Summarize" | "StyleProfile"

/**
 * The full per-account matrix (F_F4 §4.4), persisted as JSON in
 * `account_ai_settings.provider_matrix`. An empty `entries` list is valid —
 * every capability then falls back to the base provider columns.
 */
export type CapabilityMatrix = { entries: MatrixEntry[] }

/**
 * `complete_recommended_oauth` result (card §3). In-band like
 * `verify_ai_provider`: a failed connection test is `ok = false`, not an IPC
 * error — hard grant failures (state mismatch, exchange refusal) stay errors.
 */
export type CompleteRecommendedOAuthResult = { ok: boolean; providerName: string; modelName: string | null; errorMessage: string | null }

/**
 * Three-tier concession guidance (F_D2 §4.4): what we can concede, what is
 * negotiable, and what must not be conceded.
 */
export type ConcessionAdvice = { concedable: string[]; negotiable: string[]; nonConcedable: string[] }

/**
 * Provider summary for one account whose AI is configured (T068 §3). One row
 * per account with `ai_provider != 'none'`; consumed by the Settings → AI
 * Providers list and the T066 matrix UI.
 */
export type ConfiguredProviderInfo = { accountId: string; email: string; displayName: string; 
/**
 * Account color token (`terra` / `slate` / `sage` / …) for the row accent.
 */
colorToken: string; provider: AiProvider; model: string | null; baseUrl: string | null; 
/**
 * 1 = Manual Only, 2 = Semi-Auto, 3 = Full Auto.
 */
authLevel: number; 
/**
 * Local providers never send mail content off-device (F_F2 §4.5 badge).
 */
isLocal: boolean; 
/**
 * Whether an adapter or factory for this provider is registered in this
 * build (`AiRegistry::registered`) — `false` renders as unavailable.
 */
available: boolean; updatedAt: number }

/**
 * Counterparty history snapshot from `contacts` (F_D2 §4.2). `None` on the
 * wire when this is the first contact — the analysis then rests on the
 * current mail alone (F_D2 §6).
 */
export type ContactHistorySummary = { interactionCount: number; replyCount: number; 
/**
 * Parsed `contacts.style_notes` JSON; `None` when absent or unreadable.
 */
styleNotes: JsonValue | null }

/**
 * One cooling provider in the status snapshot.
 */
export type CooldownInfo = { provider: AiProvider; 
/**
 * Unix seconds when the cooldown lapses.
 */
until: number; 
/**
 * `auth` | `rate_limited` | `transient`.
 */
reason: string }

/**
 * Counterparty profile block of the D2 verdict (F_D2 §4.4): stance, tone,
 * decision-authority clues, and free-form observations.
 */
export type CounterpartyProfile = { stance: CounterpartyStance; tone: CounterpartyTone; authoritySignal: string; observations: string[] }

/**
 * Counterparty stance read from the mail (F_D2 §4.4). The model must emit
 * exactly one of these lowercase tags — anything else fails validation and
 * triggers the single re-prompt retry (T072 §3 step 7).
 */
export type CounterpartyStance = "cooperative" | "neutral" | "adversarial"

/**
 * Counterparty communication style (F_D2 §4.4).
 */
export type CounterpartyTone = "formal" | "casual"

/**
 * Parameters to create an account (T013). `password` is consumed at the command
 * boundary and handed to the Keychain — it is never persisted in the DB and is
 * stripped from the returned [`Account`].
 */
export type CreateAccountParams = { email: string; displayName: string; provider: Provider; imapHost: string | null; imapPort: number | null; smtpHost: string | null; smtpPort: number | null; colorToken: string; badgeLabel: string; roleType: string | null; roleDescription: string | null; authLevel: number | null; 
/**
 * IMAP/SMTP password (omitted for OAuth accounts). Keychain-only.
 */
password: string | null }

/**
 * `get_data_flow_ai_routing` payload: routing rows + the 24h activity summary.
 */
export type DataFlowAiRouting = { routes: AiRouteEntry[]; activity: AiActivityRow[]; 
/**
 * Unix seconds of the summary window start (`now - 24h`).
 */
sinceUnix: number }

/**
 * Aggregated statistics over a time window (F_E7 §4.6) — computed in one
 * SQLite GROUP-BY pass, never by loading rows.
 */
export type DecisionSummary = { totalEvents: number; autoSentCount: number; downgradeCount: number; sensitiveCount: number; draftSentCount: number; draftCreatedCount: number; totalInputTokens: number; totalOutputTokens: number; 
/**
 * `draft_sent / draft_created`; `0.0` when nothing was created.
 */
successRate: number }

/**
 * Per-account on-disk footprint (T020).
 */
export type DiskUsage = { totalBytes: number; attachmentBytes: number; bodyBytes: number }

/**
 * The all-providers-failed outcome of [`FallbackRouter::invoke`]
 * (F_F5 §4.2). Carried by module-E events (`draft:degraded` etc.), so it is
 * specta-exported.
 */
export type DowngradeDecision = { accountId: string; capability: Capability; 
/**
 * `all_providers_unavailable` | `context_too_long` | `user_disabled` |
 * `not_configured`.
 */
reason: string; 
/**
 * `"provider (failure)"` entries in the order they were tried —
 * identifiers and error classes only, never content (09 §5).
 */
failedChain: string[]; suggestedAction: SuggestedAction; 
/**
 * Unix seconds of the earliest cooldown expiry, when one exists.
 */
retryAfter: number | null; 
/**
 * `true` when a full-auto (E3) account must fall back to semi-auto (E2):
 * the pipeline marks the draft `pending` for human review instead of
 * sending (dev/06 §7 — never skip, never send blind).
 */
shouldDowngradeE3ToE2: boolean }

/**
 * A locally-stored compose draft (T045). Persisted to `ai_drafts` with
 * `trigger_mode='compose'` so user drafts and AI drafts share one table.
 */
export type Draft = { id: string; accountId: string; to: Recipient[]; cc: Recipient[]; subject: string; bodyText: string; bodyHtml: string | null; inReplyTo: string | null; updatedAt: number }

/**
 * `draft:discarded` payload (T080) — the draft left the review queue.
 * `reason`: `user` | `expired` | `superseded` | `sent` (consumed by approve).
 */
export type DraftDiscardedPayload = { draftId: string; reason: string | null }

/**
 * `draft:ready` payload (T077) — a generated draft landed in `ai_drafts`;
 * the UI opens the compose window / review queue from these identifiers.
 */
export type DraftReadyPayload = { draftId: string; mailId: string; 
/**
 * `E1_manual` | `E2_semi` | `E3_auto`.
 */
triggerMode: string; accountId: string }

/**
 * `draft:updated` payload (T080) — a draft body changed via
 * `update_draft_body`; identifiers only, the body travels over IPC on demand.
 */
export type DraftUpdatedPayload = { draftId: string }

/**
 * The wire `ErrorCode` (02 §2). Serialized as `SCREAMING_SNAKE_CASE` strings so
 * the TypeScript union reads e.g. `"AUTH_INVALID_CREDENTIALS"`.
 * 
 * This is the authoritative set the frontend `errors.ts` table is keyed on; a
 * `Record<ErrorCode, …>` there forces a UX decision for every code at build time
 * (09 §4, 09 §8).
 */
export type ErrorCode = "AUTH_INVALID_CREDENTIALS" | "AUTH_OAUTH_FAILED" | "AUTH_KEYCHAIN_DENIED" | "IMAP_CONNECTION_FAILED" | "IMAP_UID_VALIDITY_CHANGED" | "SMTP_SEND_FAILED" | "SMTP_RATE_LIMITED" | "DB_NOT_FOUND" | "DB_CONSTRAINT" | "DB_MIGRATION_FAILED" | "AI_PROVIDER_UNREACHABLE" | "AI_RATE_LIMITED" | "AI_CONTEXT_TOO_LONG" | "GTE_INDEX_CORRUPT" | "GTE_REINDEX_IN_PROGRESS" | "FS_PERMISSION_DENIED" | "FS_DISK_FULL" | "VALIDATION" | "NOT_FOUND" | "FORBIDDEN" | "INTERNAL"

/**
 * Params for `export_ai_decisions` (F_E7 §4.7). The export carries structured
 * fields only — `action_description`, `result_description`, and
 * `knowledge_summary` stay local (privacy boundary, T088 §6).
 */
export type ExportAiDecisionsParams = { accountId: string | null; sinceUnix: number; untilUnix: number; format: AiDecisionExportFormat }

/**
 * `export:complete`.
 */
export type ExportCompletePayload = { taskId: string; 
/**
 * Absolute path of the final `.zip` bundle.
 */
outputPath: string; 
/**
 * Absolute path of the directory holding the bundle.
 */
outputDir: string; mailCount: number }

/**
 * `export:error`.
 */
export type ExportErrorPayload = { taskId: string; code: ErrorCode; message: string }

/**
 * Export output format (F_H2 §4.1).
 */
export type ExportFormat = "mbox" | "json"

/**
 * `export:progress` — emitted once per processed batch.
 */
export type ExportProgressPayload = { taskId: string; count: number; total: number; 
/**
 * "mails" | "attachments" | "zip"
 */
stage: string }

/**
 * Returned by `start_attachment_extraction_backfill` (T108): how many downloaded
 * attachments are still awaiting text extraction.
 */
export type ExtractionBatchStarted = { pendingCount: number }

/**
 * `extraction:progress` — attachment text-extraction heartbeat (T108).
 */
export type ExtractionProgressPayload = { processed: number; total: number; indexed: number; skipped: number; errored: number }

/**
 * `gte:error` — a mail exhausted its embed retries (T031).
 */
export type GteErrorPayload = { mailId: string; reason: string }

/**
 * `gte:finished` — emitted when the pending queue drains (T031).
 */
export type GteFinishedPayload = { totalIndexed: number; elapsedMs: number }

/**
 * `gte:progress` — embedding pipeline heartbeat (T031, B3).
 */
export type GteProgressPayload = { 
/**
 * Mails indexed so far this worker session.
 */
indexed: number; 
/**
 * Mails still in `embedding_status='pending'`.
 */
totalPending: number; 
/**
 * Smoothed indexing rate (mails/second).
 */
ratePerSec: number }

/**
 * One Agent-IM channel message (`im_messages`, T092). The TEAM channel is a
 * single shared room — `channel_id` is always `"main"` (no private chats).
 */
export type ImMessage = { id: string; channelId: string; 
/**
 * `human` | `agent` | `system`.
 */
senderType: string; 
/**
 * Account id for `agent`; `"human"` / `"system"` for the other senders.
 */
senderId: string; 
/**
 * `text` | `query_card` | `card_reply` | `status`.
 */
messageType: string; 
/**
 * JSON payload; shape depends on `message_type` (text → `{ "text": "…" }`).
 */
content: string; linkedEmailId: string | null; 
/**
 * `pending` | `answered` | `skipped` | `resolved` (query-card lifecycle).
 */
status: string; createdAt: number; readAt: number | null }

/**
 * Scope for a remote-image allow decision (T029). Tagged union → TS discriminated
 * union (`{ type: "thisMessage" } | { type: "alwaysSender", senderEmail }`).
 */
export type ImageAllowScope = { type: "thisMessage" } | { type: "alwaysSender"; senderEmail: string }

/**
 * Remote-image loading policy, three levels (F_B1). Persisted at
 * `app_settings.privacy.remote_image_policy`; default `BlockAll`.
 */
export type ImagePolicy = "block_all" | "trusted_only" | "allow_all"

/**
 * The serialized wire error (02 §2). Tauri throws the `Err` variant of a
 * command's `Result` to JS in this shape.
 */
export type IpcError = { code: ErrorCode; 
/**
 * Human-readable English fallback (the UI prefers the localized key, 09 §4).
 */
message: string; 
/**
 * Technical detail for logging; `null` when there is none. Never rendered raw.
 */
detail: string | null }

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }

/**
 * Params for `keyword_search` (02 §Module C). `limit`/`offset` come from
 * `PageParams`; the backend clamps `limit` to `[1, 200]`.
 */
export type KeywordSearchParams = { query: string; accountId: string | null; dateFrom: number | null; dateTo: number | null; folder: string | null; limit: number; offset: number }

/**
 * The D1 legal analysis verdict returned to the frontend (T070 §3). Also the
 * exact JSON persisted in `ai_decisions.action_description`, which backs the
 * 24-hour result cache.
 */
export type LegalAnalysisResult = { 
/**
 * `ai_decisions.id` of this analysis (the E7 audit row).
 */
decisionId: string; mailId: string; accountId: string; riskList: LegalRiskItem[]; keyClauses: LegalKeyClauses; complianceAdvice: string[]; 
/**
 * Derived: the worst `riskList[].level` (T070 §6).
 */
overallLevel: LegalOverallLevel; aiModel: string; 
/**
 * Mail ids of the GTE chunks that grounded the analysis (dev/06 §9).
 */
knowledgeRefs: string[]; createdAt: number }

/**
 * Standard key-clause extraction (F_D1 §4.4). Clauses the model did not find
 * are `None` and the UI renders them as absent.
 */
export type LegalKeyClauses = { payment: string | null; delivery: string | null; liability: string | null; confidentiality: string | null; disputeResolution: string | null }

/**
 * Worst-of aggregate over `riskList` (T070 §3): `high` maps to a T4 alert,
 * `none` means the analysis found no risks at all.
 */
export type LegalOverallLevel = "high" | "medium" | "low" | "none"

/**
 * One identified risk (F_D1 §4.4). `originalText` is capped at 120 chars and
 * `finding`/`suggestion` at 80 chars — enforced defensively at parse time.
 */
export type LegalRiskItem = { level: LegalRiskLevel; type: LegalRiskType; originalText: string; finding: string; suggestion: string }

/**
 * Severity of one identified risk item (D1 output schema, F_D1 §4.4). The
 * model must emit exactly one of these lowercase tags — anything else fails
 * validation and triggers the single re-prompt retry (T070 §3 step 6).
 */
export type LegalRiskLevel = "high" | "medium" | "low"

/**
 * D1 risk category (F_D1 §4.4). Mapped to `risk_events.risk_type` by the
 * legal pipeline (T070 §6).
 */
export type LegalRiskType = "payment" | "delivery" | "liability" | "confidentiality" | "dispute" | "other"

/**
 * Filter for `list_pending_drafts` (T080, 02 §Module E).
 */
export type ListAiDraftsParams = { 
/**
 * `null` = all accounts.
 */
accountId: string | null; 
/**
 * Default 50, capped at 200.
 */
limit: number | null }

/**
 * Filters for `list_ai_decisions` (F_E7 §4.5). All fields optional; `limit`
 * defaults to and is capped at 200, newest first.
 */
export type ListDecisionsParams = { accountId: string | null; sinceUnix: number | null; untilUnix: number | null; 
/**
 * Restrict to these `decision_type` values (empty/None = all).
 */
decisionTypes: string[] | null; impact: string | null; limit: number | null; offset: number | null }

/**
 * One reachable local AI endpoint found by `scan_local_providers` (F_F2 §3).
 */
export type LocalProviderEndpoint = { 
/**
 * Normalized base URL, e.g. `http://localhost:11434`.
 */
baseUrl: string; 
/**
 * Daemon kind behind the endpoint; v0.5 probes Ollama defaults only.
 */
provider: AiProvider }

/**
 * Lightweight mail row for lists + the `mail:new` event payload (T023/T024).
 */
export type MailSummary = { id: string; accountId: string; threadId: string | null; subject: string; fromName: string | null; fromEmail: string; snippet: string | null; dateSent: number; isRead: boolean; hasAttachments: boolean }

/**
 * `mail:updated` — partial field update for one mail.
 */
export type MailUpdatedPayload = { id: string; isRead: boolean | null; isStarred: boolean | null }

/**
 * The assignment for one `(capability, account)` cell: a required primary
 * plus an ordered fallback chain (F_F4 §4.2). `resolve()` only ever returns
 * the primary; T067 walks `backups` after a primary failure via
 * [`AiRegistry::resolve_backup`](super::registry::AiRegistry::resolve_backup).
 */
export type MatrixCell = { primary: ProviderAssignment; backups?: ProviderAssignment[] }

/**
 * One matrix row binding for an account: capability → cell.
 */
export type MatrixEntry = { capability: Capability; cell: MatrixCell }

/**
 * One non-blocking save-time hint (F_F4 §4.5). `code` is a stable tag the
 * frontend maps to localized copy; `message` is the English fallback.
 */
export type MatrixWarning = { capability: Capability; code: string; message: string }

/**
 * One explicit or between-the-lines need (F_D2 §4.4). `evidence` is an
 * original-text snippet capped at 80 chars — enforced defensively at parse
 * time.
 */
export type NeedItem = { need: string; priority: NeedPriority; evidence: string }

/**
 * Priority of one identified need (F_D2 §4.4).
 */
export type NeedPriority = "high" | "medium" | "low"

/**
 * One recommended next step with its execution window (F_D2 §4.4).
 */
export type NextAction = { action: string; timeline: NextActionTimeline }

/**
 * Suggested execution window for one next action (F_D2 §4.4). Wire tags are
 * the D2 schema literals: `immediate` / `24h` / `72h` / `this_week`.
 */
export type NextActionTimeline = "immediate" | "24h" | "72h" | "this_week"

/**
 * What `begin_oauth_flow` returns to the UI (T015): just the authorize URL to
 * open. The PKCE verifier stays server-side; tokens never reach the frontend.
 */
export type OAuthBeginResult = { authorizeUrl: string }

/**
 * One model installed on a local daemon (F_F2 §4.3) — the wire shape of
 * `list_ollama_models`, projected from the adapter's `OllamaModelInfo`.
 */
export type OllamaModelEntry = { 
/**
 * Full model tag, e.g. `llama3:8b`.
 */
name: string; 
/**
 * On-disk weight size in bytes (0 when the daemon omits it).
 */
sizeBytes: number; 
/**
 * e.g. `8B` — from the daemon's `details.parameter_size`.
 */
parameterSize: string | null; 
/**
 * e.g. `Q4_0` — from the daemon's `details.quantization_level`.
 */
quantization: string | null }

/**
 * Generic paginated envelope (02 §Pagination). `total` is the full match count
 * so the UI can render pagination without a second query.
 */
export type PageResult<T> = { items: T[]; total: number; offset: number }

/**
 * One proactive query awaiting a human decision (`pending_queries`, T095/I3).
 * `content`-rich rendering lives in the `im_messages` query card (T098); this is
 * the lifecycle row the Pending DecisionCard (T099) and resume/expiry chains
 * (T096/T097) act on.
 */
export type PendingQuery = { id: string; accountId: string; mailId: string | null; riskEventId: string | null; 
/**
 * `T1`–`T6`.
 */
triggerType: string; question: string; 
/**
 * JSON array of option labels (the rich QA card content lives in im_messages).
 */
options: string | null; answer: string | null; 
/**
 * `pending` | `answered` | `skipped` | `expired`.
 */
status: string; 
/**
 * 1 (highest) – 5; T4 is always 1.
 */
priority: number; 
/**
 * `None` for T4 (never expires); otherwise `created_at + 72h`.
 */
expiresAt: number | null; answeredAt: number | null; createdAt: number }

/**
 * Result of the `ping` command — the first end-to-end IPC roundtrip (T002).
 * 
 * Started life as a bare `String` in T002 and was promoted to a named DTO in
 * T003 to establish the "every wire value is a named, generated type" pattern.
 */
export type PingReply = { 
/**
 * Always `"pong"` for a healthy backend.
 */
message: string }

/**
 * `pipeline:error` payload (T082) — one background pipeline job failed;
 * `error_code` is the wire `ErrorCode` string, never message text.
 */
export type PipelineErrorPayload = { mailId: string; errorCode: string }

/**
 * Mail provider family. Drives OAuth endpoint selection (T015) and is persisted
 * in `accounts.provider` as a lowercase string.
 */
export type Provider = "gmail" | "outlook" | "imap" | "exchange"

/**
 * One provider + model choice inside a cell (F_F4 §4.2).
 */
export type ProviderAssignment = { provider: AiProvider; 
/**
 * Model name at that provider. An empty string means "the provider's
 * default" (the local ONNX adapter auto-selects from its models folder).
 */
model: string; 
/**
 * Custom endpoint override; `None` = the provider's standard endpoint
 * (or, when the assignment keeps the account's base provider, the base
 * `ai_base_url`).
 */
baseUrl: string | null }

/**
 * Built-in provider connection hints (T014 autodiscover).
 */
export type ProviderHints = { imapHost: string; imapPort: number; imapTls: boolean; smtpHost: string; smtpPort: number; smtpTls: boolean }

export type QaCardContent = { cardVersion: number; 
/**
 * `pending_queries.id` this card resolves (used by T096 answer/skip).
 */
linkedQueryId: string; triggerType: string; 
/**
 * `high` | `normal` | `low`.
 */
priority: string; linkedEmailId: string | null; questionText: string; options: QaCardOption[]; multiSelect: boolean; freeTextPlaceholder: string | null; subQuestions: QaCardSubQuestion[]; response: QaCardResponse | null }

export type QaCardOption = { id: string; label: string; value: string }

export type QaCardResponse = { selectedOptionIds: string[]; freeText: string | null; submittedAt: number; actionResult: string | null }

export type QaCardSubQuestion = { questionText: string; options: QaCardOption[]; multiSelect: boolean }

/**
 * `query:expired` payload (T097/T101) — a query auto-expired (non-T4) or fired a
 * T4 reminder. Identifiers only.
 */
export type QueryExpiredPayload = { queryId: string; accountId: string; triggerType: string }

/**
 * `query:new` payload (T095/T101) — a proactive query was raised. Identifiers
 * only; `priority` is `"high"` (push a notification) or `"normal"` (badge only).
 */
export type QueryNewPayload = { queryId: string; accountId: string; priority: string }

/**
 * One knowledge-depth time bucket's estimate (T016). `None` fields mean the
 * sample timed out / couldn't be computed.
 */
export type RangeEstimate = { 
/**
 * `None` = "all mail"; `Some(n)` = last `n` months.
 */
months: number | null; mailCount: number | null; estimatedMb: number | null }

/**
 * One recipient (compose + send). `name` is optional; `email` is required.
 */
export type Recipient = { name: string | null; email: string }

/**
 * Payload of the [`OAUTH_CALLBACK_EVENT`] the deep-link handler emits.
 */
export type RecommendedOAuthCallback = { code: string; state: string }

/**
 * What the wizard renders per tier (F_F3 §3 step 2 + §4.4). Endpoint URLs
 * and env names are deliberately absent — the frontend never needs them.
 */
export type RecommendedProviderInfo = { tier: RecommendedTier; provider: AiProvider; model: string; displayName: string; monthlyCostMinUsd: number; monthlyCostMaxUsd: number; tokensPerReplyEstimate: number; 
/**
 * `false` = the wizard must use the authorization-code paste fallback.
 */
oauthSupported: boolean }

/**
 * The two recommendation tiers (F_F3 §3 step 2).
 */
export type RecommendedTier = "balanced" | "high_quality"

/**
 * Params for `regenerate_draft` (02 §Module E): supersede an existing draft
 * and generate a fresh one for the same trigger mail.
 */
export type RegenerateDraftParams = { 
/**
 * The draft being regenerated (it ends up `discarded`/`superseded`).
 */
id: string; instruction: string | null }

/**
 * Params for `request_ai_reply` (02 §Module E): generate an E1 manual reply
 * draft for one mail, with an optional steering instruction.
 */
export type RequestAiReplyParams = { mailId: string; instruction: string | null }

/**
 * `risk:alert` payload (T084) — an E4 interception (or any new risk event)
 * the UI should refetch risk queries for. Identifiers only.
 */
export type RiskAlertPayload = { riskEventId: string; mailId: string; accountId: string }

/**
 * The D2 sales analysis returned to the frontend (T072 §3). Also the exact
 * JSON persisted in `ai_decisions.action_description`, which backs the
 * 24-hour result cache.
 */
export type SalesAnalysisResult = { 
/**
 * `ai_decisions.id` of this analysis (the E7 audit row).
 */
decisionId: string; mailId: string; accountId: string; counterpartyProfile: CounterpartyProfile; needsAndIntents: NeedItem[]; concessionAdvice: ConcessionAdvice; nextActions: NextAction[]; 
/**
 * `None` when the counterparty has no `contacts` row (first contact).
 */
contactHistory: ContactHistorySummary | null; aiModel: string; 
/**
 * Mail ids of the GTE chunks that grounded the analysis (dev/06 §9).
 */
knowledgeRefs: string[]; createdAt: number }

/**
 * The six-bucket mailbox sample (T016).
 */
export type SamplingResult = { ranges: RangeEstimate[] }

/**
 * Params to upsert a compose draft (T045). `id` absent → create.
 */
export type SaveDraftParams = { id: string | null; accountId: string; to?: Recipient[]; cc?: Recipient[]; subject: string; bodyText: string; bodyHtml: string | null; inReplyTo: string | null }

/**
 * Params to create a saved search (T035).
 */
export type SaveSearchParams = { name: string; query: string; mode: string; accountId: string | null }

/**
 * A persisted saved search (01 `saved_searches`, T035).
 */
export type SavedSearch = { id: string; accountId: string | null; name: string; query: string; mode: string; sortOrder: number; createdAt: number }

/**
 * Relevance bucket for a result row (02 §SearchResult). high ≥ 0.7, mid ≥ 0.4.
 */
export type ScoreLabel = "high" | "mid" | "low"

/**
 * One recent search (01 `search_history`, T032/T034).
 */
export type SearchHistoryItem = { id: number; query: string; mode: string; resultCount: number | null; createdAt: number }

/**
 * Which search the combined command runs for the mail hits (T110).
 */
export type SearchMode = "keyword" | "semantic" | "auto"

/**
 * A single search hit, shared by keyword (C1) and semantic (C2) search.
 */
export type SearchResult = { mailId: string; accountId: string; subject: string; fromName: string | null; fromEmail: string; dateSent: number; snippet: string; 
/**
 * 0.0–1.0 — keyword: normalised BM25; semantic: cosine.
 */
score: number; scoreLabel: ScoreLabel; 
/**
 * Matched fragments with `<mark>…</mark>` tags (keyword search only).
 */
highlights: string[] }

/**
 * Params for `search_with_attachments` (T110 §3a).
 */
export type SearchWithAttachmentsParams = { query: string; mode: SearchMode; accountId: string | null; dateFrom: number | null; dateTo: number | null; limit: number | null }

/**
 * Combined result: mail-body hits + attachment-origin hits (T110 §3a).
 */
export type SearchWithAttachmentsResult = { mailHits: SearchResult[]; attachmentHits: AttachmentHit[] }

/**
 * Params for `semantic_search` (02 §Module C).
 */
export type SemanticSearchParams = { query: string; accountId: string | null; 
/**
 * Cross-account subset filter (T112). `None` = every active account;
 * `Some(ids)` = only those accounts. `account_id`, when set, takes
 * precedence (single-account path) for backward compatibility.
 */
accountFilter: string[] | null; dateFrom: number | null; dateTo: number | null; 
/**
 * Minimum cosine score; defaults to 0.35 when absent.
 */
minScore: number | null; limit: number; offset: number }

/**
 * Params for `send_mail` (02 §Module B/G). Recipients are typed addresses; the
 * HTML body is optional (plain-text-only messages are valid).
 */
export type SendMailParams = { accountId: string; to: Recipient[]; cc?: Recipient[]; bcc?: Recipient[]; subject: string; bodyText: string; bodyHtml: string | null; 
/**
 * Message-ID this is a reply to (drives thread association).
 */
inReplyTo: string | null; 
/**
 * Space-separated References chain (RFC 2822).
 */
references: string | null; 
/**
 * The draft this send finalises, if any (deleted on success, T045).
 */
draftId: string | null }

/**
 * `send_mail` result — the pending id (for cancel) + the message id (02 §3).
 */
export type SendMailResult = { pendingId: string; messageId: string }

/**
 * Parameters for `start_export` (T052). Credentials are structurally absent —
 * the export pipeline reads only `mails`/`attachments` rows.
 */
export type StartExportParams = { accountIds: string[]; 
/**
 * Unix seconds, inclusive lower bound. `None` = no lower bound.
 */
dateFrom: number | null; 
/**
 * Unix seconds, inclusive upper bound. `None` = no upper bound.
 */
dateTo: number | null; format: ExportFormat; includeBody: boolean; includeAttachments: boolean }

/**
 * `style:done` — the profile was written (or, for a pinned profile, the
 * sample count was refreshed).
 */
export type StyleDonePayload = { accountId: string; sampleCount: number }

/**
 * `style:error` — the run failed; `code` follows the standard wire table
 * (insufficient samples surfaces as `VALIDATION`, AI_MODES §6.7).
 */
export type StyleErrorPayload = { accountId: string; code: ErrorCode }

/**
 * The persisted style profile — stored verbatim in
 * `account_ai_settings.style_profile` and read back by T076 prompt injection
 * and the settings UI. Keys are deliberately `snake_case` (the stored schema
 * of F_E5 §4.2), unlike the camelCase event payloads below.
 */
export type StyleProfileJson = { version: number; account_id: string; 
/**
 * Unix timestamp (seconds) — drives the 30-day refresh check.
 */
generated_at: number; summary: StyleSummary; 
/**
 * Local-audit snippets (≤ 3 × 100 chars). Never injected into prompts.
 */
sample_snippets: string[]; 
/**
 * Set by the user when they hand-edit the summary (F_E5 §4.5); a pinned
 * profile is never overwritten by recomputes.
 */
pinned?: boolean }

/**
 * `style:progress` — one emission per stage: sampling → profiling → done.
 */
export type StyleProgressPayload = { accountId: string; 
/**
 * "sampling" | "profiling" | "done"
 */
stage: string; pct: number }

/**
 * The six style dimensions (F_E5 §4.2). Each text field is a short free-text
 * description (≤ ~80 words, enforced by prompt).
 */
export type StyleSummary = { overall_tone: string; opening_patterns: string[]; closing_patterns: string[]; sentence_length: string; vocabulary: string; format_habit: string }

/**
 * What the caller should do with the task that could not be served
 * (F_F5 §4.2). Every option keeps or increases human control — there is no
 * "send anyway" action by design (dev/06 §7 golden rule).
 */
export type SuggestedAction = 
/**
 * Keep the task queued; replay when a provider recovers (E2/E3, E5).
 */
"hold" | 
/**
 * Drop this background task; the per-account offline policy decides how
 * the mail is treated (E4 sensitivity pre-scan).
 */
"skip" | 
/**
 * Tell the human; the action was user-triggered (E1/D1/D2) or needs a
 * configuration fix.
 */
"prompt_user"

/**
 * `sync:complete`.
 */
export type SyncCompletePayload = { accountId: string; newCount: number }

/**
 * `sync:error`.
 */
export type SyncErrorPayload = { accountId: string; code: ErrorCode; message: string }

/**
 * `sync:progress`.
 */
export type SyncProgressPayload = { accountId: string; fetched: number; total: number | null; paused: boolean }

/**
 * Preview for a sync-range shrink (how many local mails fall outside).
 */
export type SyncRangePreview = { mailsBeyondRange: number }

/**
 * `sync:started`.
 */
export type SyncStartedPayload = { accountId: string }

/**
 * Per-account IMAP sync bookmark + health (01 `sync_state`, T021).
 */
export type SyncState = { accountId: string; lastSyncAt: number | null; lastSyncResult: string | null; consecutiveErrors: number; backoffUntil: number | null; inboxUidValidity: number | null; inboxUidNext: number | null; fullSyncRequired: boolean; totalMailsSynced: number; updatedAt: number }

/**
 * Tracker/remote-image status for one mail (T029).
 */
export type TrackerInfo = { blocked: boolean; trackerCount: number; imagesAllowed: boolean; senderEmail: string }

/**
 * Tracker-blocking policy, three levels (F_B2 §4.4). Persisted at
 * `app_settings.privacy.tracker_policy`; default `BlockKnown` (protection ON).
 */
export type TrackerPolicy = "block_all" | "block_known" | "allow_all"

/**
 * Partial update for an account (T013). `email` is intentionally absent — it is
 * immutable once an account is created.
 */
export type UpdateAccountParams = { displayName: string | null; colorToken: string | null; badgeLabel: string | null; roleType: string | null; roleDescription: string | null; authLevel: number | null; isActive: boolean | null; isPrimary: boolean | null; syncIntervalSecs: number | null; imapHost: string | null; imapPort: number | null; smtpHost: string | null; smtpPort: number | null }

/**
 * Partial update for `account_ai_settings` (02 §Module H). `ai_api_key` is
 * consumed at the command boundary and written to the Keychain — it is never
 * stored in a DB column and never echoed back to the frontend.
 */
export type UpdateAiSettingsParams = { authLevel: number | null; aiProvider: AiProvider | null; aiModel: string | null; 
/**
 * Written to the Keychain at the boundary; `None` = leave unchanged.
 */
aiApiKey: string | null; aiBaseUrl: string | null; t1Enabled: boolean | null; t2Enabled: boolean | null; t3Enabled: boolean | null; t4Enabled: boolean | null; t5Enabled: boolean | null; t6Enabled: boolean | null; dailyQueryLimit: number | null; e3WhitelistOnly: boolean | null; e3MinHistory: number | null }

/**
 * Outcome of an `upsert_batch` (T023).
 */
export type UpsertStats = { inserted: number; skippedDuplicate: number; parseErrors: number }

/**
 * Input to `verify_ai_provider` (02 §Module H): test a provider key/endpoint
 * without saving. The transient key exists only inside the command frame.
 */
export type VerifyAiProviderParams = { provider: AiProvider; model: string; apiKey: string | null; baseUrl: string | null }

/**
 * In-band result of `verify_ai_provider` (02 §Module H). The command returns
 * `Ok(_)` even when the probe fails (09 §2 in-band bucket); `error_message`
 * carries only the sanitized, content-free `ProviderError` rendering.
 */
export type VerifyAiProviderResult = { ok: boolean; 
/**
 * Confirmed model name from the provider, when it reports one.
 */
modelName: string | null; errorMessage: string | null }

/**
 * Input to the connection probe (T014). Plaintext `password` exists only inside
 * the probe's call frame; it is not stored anywhere.
 */
export type VerifyConnectionParams = { email: string; provider: Provider; password: string | null; imapHost: string | null; imapPort: number | null; imapTls: boolean | null; smtpHost: string | null; smtpPort: number | null; smtpTls: boolean | null }

/**
 * In-band probe result (T014). The command returns `Ok(_)` even on probe
 * failure; only internal errors escalate to `IpcError` (09 §2).
 */
export type VerifyConnectionResult = { imapOk: boolean; smtpOk: boolean; errorMessage: string | null }

/**
 * `wipe:complete`. `freed_bytes` is the estimate confirmed after VACUUM.
 */
export type WipeCompletePayload = { taskId: string; freedBytes: number }

/**
 * Impact preview shown before the `DELETE` confirmation step.
 */
export type WipePreview = { mailCount: number; attachmentCount: number; estimatedBytes: number }

/**
 * `wipe:progress` — emitted per deleted batch.
 */
export type WipeProgressPayload = { taskId: string; deleted: number; total: number }

/**
 * What a wipe removes (F_H2 §4.2 two-tier + full removal).
 */
export type WipeScope = 
/**
 * mails/threads/attachments rows + blobs; index untouched.
 */
"mails_only" | 
/**
 * Same + LanceDB vectors and FTS entries.
 */
"mails_and_index" | 
/**
 * Same + the account configuration row itself.
 */
"everything"

// ── Mail-list view types (G2/G3) ─────────────────────────────────────────────
// PROVISIONAL: these mirror dev/02 §"Module B" list contracts. The mail-list
// read backend (list_threads / list_mails / get_mail) is a separate card; until
// it lands these are served by the dev mock layer (ipc/client.ts). When that card
// ships, these become specta-generated like the rest of this file.

export type Thread = {
  id: string;
  accountId: string;
  subject: string;
  participants: string[];
  mailCount: number;
  unreadCount: number;
  hasAttachments: boolean;
  latestDate: number;
  snippet: string | null;
  isArchived: boolean;
  isStarred: boolean;
};

export type ListThreadsParams = {
  accountId?: string | null;
  folder?: string | null;
  isArchived?: boolean | null;
  hasUnread?: boolean | null;
  limit: number;
  offset: number;
};

export type ListMailsParams = {
  accountId?: string | null;
  threadId?: string | null;
  folder?: string | null;
  isUnread?: boolean | null;
  dateFrom?: number | null;
  dateTo?: number | null;
  limit: number;
  offset: number;
};

export type MailDetail = {
  id: string;
  accountId: string;
  threadId: string | null;
  subject: string;
  fromName: string | null;
  fromEmail: string;
  to: Recipient[];
  cc: Recipient[];
  dateSent: number;
  bodyHtml: string | null;
  bodyText: string | null;
  isRead: boolean;
  isStarred: boolean;
  isArchived: boolean;
  hasAttachments: boolean;
  folder: string;
};

// NOTE: AutoSentPayload / AutoLoopDetectedPayload / PipelineErrorPayload used to
// be hand-written here, but they are now registered from `crate::types` above and
// emitted in the generated section — keeping the manual copies produced duplicate
// identifiers on regeneration, so they were removed (T101 cleanup).

// ── Module E — E7 audit log decision types (dev/01 §ai_decisions) ───────────

/**
 * Known `ai_decisions.decision_type` values (dev/01 §ai_decisions). The wire
 * field stays `string` so unknown backend additions degrade gracefully in the
 * UI (chip falls back to the neutral token color).
 */
export const DECISION_TYPES = [
  "draft_created",
  "draft_sent",
  "draft_discarded",
  "draft_expired",
  "e3_auto_sent",
  "auto_reply_sent",
  "risk_intercepted",
  "e4_sensitive",
  "trust_downgraded",
] as const;

export type DecisionType = (typeof DECISION_TYPES)[number];
