//! specta → TypeScript bindings exporter (T003).
//!
//! Rust DTOs are the single source of truth. This module collects the wire types
//! and renders `packages/shared/src/bindings.ts`. It is compiled ONLY under the
//! `specta-export` feature (the `gen-bindings` bin), so the shipping app never
//! links `specta-typescript`.
//!
//! `pnpm gen:types` runs the `gen-bindings` bin; CI then runs it and
//! `git diff --exit-code packages/shared/src/bindings.ts` so a changed Rust type
//! that wasn't regenerated fails the build (08 §6, 02 §6).
//!
//! NOTE: specta v2 / specta-typescript are pre-1.0 (rc). If the resolved patch
//! version changes the collection/export entry points, this single function is
//! the only place to adjust — the frontend depends on the committed `bindings.ts`,
//! not on this code path.

use specta::{Language, NamedType, TypeMap};
use specta_typescript::{BigIntExportBehavior, Typescript};

const HEADER: &str = "// @generated by `pnpm gen:types` from Rust types (specta). DO NOT EDIT.\n// Source of truth: src-tauri/src/types.rs and src-tauri/src/error.rs (T003).\n";

/// Wire types the frontend needs that have no Rust DTO yet, appended verbatim
/// after the generated section. Two groups:
///
/// - Mail-list read contracts (G2/G3): `list_threads` / `list_mails` / `get_mail`
///   are still served by the dev mock layer (`src/ipc/client.ts`); when that
///   backend card lands, move these to `types.rs` and register them above.
/// - E3 full-auto event payloads (T085/T086) and the `ai_decisions` decision-type
///   value list (the Rust side keeps `decision_type` as a free `string` column).
const PROVISIONAL_APPENDIX: &str = r#"// ── Mail-list view types (G2/G3) ─────────────────────────────────────────────
// PROVISIONAL: these mirror dev/02 §"Module B" list contracts. The mail-list
// read backend (list_threads / list_mails / get_mail) is a separate card; until
// it lands these are served by the dev mock layer (ipc/client.ts). When that card
// ships, these become specta-generated like the rest of this file.

export type Thread = {
  id: string;
  accountId: string;
  subject: string;
  participants: string[];
  mailCount: number;
  unreadCount: number;
  hasAttachments: boolean;
  latestDate: number;
  snippet: string | null;
  isArchived: boolean;
  isStarred: boolean;
};

export type ListThreadsParams = {
  accountId?: string | null;
  folder?: string | null;
  isArchived?: boolean | null;
  hasUnread?: boolean | null;
  limit: number;
  offset: number;
};

export type ListMailsParams = {
  accountId?: string | null;
  threadId?: string | null;
  folder?: string | null;
  isUnread?: boolean | null;
  dateFrom?: number | null;
  dateTo?: number | null;
  limit: number;
  offset: number;
};

export type MailDetail = {
  id: string;
  accountId: string;
  threadId: string | null;
  subject: string;
  fromName: string | null;
  fromEmail: string;
  to: Recipient[];
  cc: Recipient[];
  dateSent: number;
  bodyHtml: string | null;
  bodyText: string | null;
  isRead: boolean;
  isStarred: boolean;
  isArchived: boolean;
  hasAttachments: boolean;
  folder: string;
};

// NOTE: AutoSentPayload / AutoLoopDetectedPayload / PipelineErrorPayload used to
// be hand-written here, but they are now registered from `crate::types` above and
// emitted in the generated section — keeping the manual copies produced duplicate
// identifiers on regeneration, so they were removed (T101 cleanup).

// ── Module E — E7 audit log decision types (dev/01 §ai_decisions) ───────────

/**
 * Known `ai_decisions.decision_type` values (dev/01 §ai_decisions). The wire
 * field stays `string` so unknown backend additions degrade gracefully in the
 * UI (chip falls back to the neutral token color).
 */
export const DECISION_TYPES = [
  "draft_created",
  "draft_sent",
  "draft_discarded",
  "draft_expired",
  "e3_auto_sent",
  "auto_reply_sent",
  "risk_intercepted",
  "e4_sensitive",
  "trust_downgraded",
] as const;

export type DecisionType = (typeof DECISION_TYPES)[number];
"#;

/// Registration shim over rc.20's `TypeMap` (rc.20 has no `TypeCollection`).
/// `definition_named_data_type` walks the type, pulling every referenced named
/// type into the shared map; inserting under `T::sid()` makes the registered
/// type itself part of the export set (generic types like `PageResult<T>` are
/// stored once, as their generic definition, regardless of the instantiation
/// used to register them).
struct TypeRegistry {
    map: TypeMap,
}

impl TypeRegistry {
    fn register<T: NamedType>(&mut self) {
        let ndt = T::definition_named_data_type(&mut self.map);
        self.map.insert(T::sid(), ndt);
    }
}

/// Render the wire types to `out_path`. Register every type the frontend imports
/// from `@shared/bindings` here.
pub fn export_bindings(out_path: &str) -> anyhow::Result<()> {
    let mut types = TypeRegistry {
        map: TypeMap::default(),
    };
    types.register::<crate::types::PingReply>();
    types.register::<crate::types::ErrorCode>();
    types.register::<crate::error::IpcError>();

    // ── Module A/B DTOs (T013–T029) ─────────────────────────────────────────
    types.register::<crate::types::Provider>();
    types.register::<crate::types::Account>();
    types.register::<crate::types::CreateAccountParams>();
    types.register::<crate::types::UpdateAccountParams>();
    types.register::<crate::types::OAuthBeginResult>();
    // ── SeekerMail ID identity (A6, T121) ───────────────────────────────────
    types.register::<crate::types::SeekerMailId>();
    types.register::<crate::types::ProviderHints>();
    types.register::<crate::types::VerifyConnectionParams>();
    types.register::<crate::types::VerifyConnectionResult>();
    types.register::<crate::types::RangeEstimate>();
    types.register::<crate::types::SamplingResult>();
    types.register::<crate::types::DiskUsage>();
    types.register::<crate::types::SyncState>();
    types.register::<crate::types::BackfillStatus>();
    types.register::<crate::types::UpsertStats>();
    types.register::<crate::types::MailSummary>();
    types.register::<crate::types::Attachment>();
    types.register::<crate::types::TrackerInfo>();
    types.register::<crate::types::ImageAllowScope>();
    // Event payloads (T024).
    types.register::<crate::types::SyncStartedPayload>();
    types.register::<crate::types::SyncProgressPayload>();
    types.register::<crate::types::SyncCompletePayload>();
    types.register::<crate::types::SyncErrorPayload>();
    types.register::<crate::types::MailUpdatedPayload>();
    types.register::<crate::types::AttachmentProgressPayload>();
    types.register::<crate::types::AttachmentReadyPayload>();

    // ── Attachment extraction + index (T108/T109) ───────────────────────────
    types.register::<crate::types::ExtractionBatchStarted>();
    types.register::<crate::types::ExtractionProgressPayload>();
    types.register::<crate::types::AttachmentIndexBuildStatus>();
    types.register::<crate::types::AttachmentIndexProgressPayload>();

    // ── GTE pipeline events (T031) ──────────────────────────────────────────
    types.register::<crate::types::GteProgressPayload>();
    types.register::<crate::types::GteFinishedPayload>();
    types.register::<crate::types::GteErrorPayload>();

    // ── Module C — Search (T032/T033/T035) ──────────────────────────────────
    types.register::<crate::types::ScoreLabel>();
    types.register::<crate::types::SearchResult>();
    types.register::<crate::types::KeywordSearchParams>();
    types.register::<crate::types::SemanticSearchParams>();
    types.register::<crate::types::SavedSearch>();
    types.register::<crate::types::SaveSearchParams>();
    types.register::<crate::types::SearchHistoryItem>();
    types.register::<crate::types::PageResult<crate::types::SearchResult>>();
    // ── Attachment-hit search (T110) ────────────────────────────────────────
    types.register::<crate::types::SearchMode>();
    types.register::<crate::types::SearchWithAttachmentsParams>();
    types.register::<crate::types::AttachmentHit>();
    types.register::<crate::types::SearchWithAttachmentsResult>();

    // ── Settings & privacy (T050/T051) ──────────────────────────────────────
    types.register::<crate::types::TrackerPolicy>();
    types.register::<crate::types::ImagePolicy>();

    // ── Export (T052) ────────────────────────────────────────────────────────
    types.register::<crate::types::ExportFormat>();
    types.register::<crate::types::StartExportParams>();
    types.register::<crate::types::ExportProgressPayload>();
    types.register::<crate::types::ExportCompletePayload>();
    types.register::<crate::types::ExportErrorPayload>();

    // ── Wipe / reindex / sync range (T053) ──────────────────────────────────
    types.register::<crate::types::WipeScope>();
    types.register::<crate::types::WipePreview>();
    types.register::<crate::types::WipeProgressPayload>();
    types.register::<crate::types::WipeCompletePayload>();
    types.register::<crate::types::SyncRangePreview>();

    // ── Module F — BYO AI providers (T059, Module H) ────────────────────────
    types.register::<crate::types::AiProvider>();
    types.register::<crate::types::AccountAiSettings>();
    types.register::<crate::types::UpdateAiSettingsParams>();
    types.register::<crate::types::VerifyAiProviderParams>();
    types.register::<crate::types::VerifyAiProviderResult>();

    // ── F4 capability×account matrix (T065) ─────────────────────────────────
    types.register::<crate::ai::types::Capability>();
    types.register::<crate::ai::matrix::ProviderAssignment>();
    types.register::<crate::ai::matrix::MatrixCell>();
    types.register::<crate::ai::matrix::MatrixEntry>();
    types.register::<crate::ai::matrix::CapabilityMatrix>();
    types.register::<crate::ai::matrix::MatrixWarning>();
    types.register::<crate::ai::matrix::BatchMatrixUpdate>();

    // ── D1 legal role analysis (T070) ───────────────────────────────────────
    types.register::<crate::types::LegalRiskLevel>();
    types.register::<crate::types::LegalOverallLevel>();
    types.register::<crate::types::LegalRiskType>();
    types.register::<crate::types::LegalRiskItem>();
    types.register::<crate::types::LegalKeyClauses>();
    types.register::<crate::types::AnalyzeLegalRiskParams>();
    types.register::<crate::types::LegalAnalysisResult>();

    // ── Module E risk events (T071) ─────────────────────────────────────────
    types.register::<crate::types::RiskEvent>();
    types.register::<crate::types::ListRiskEventsParams>();
    types.register::<crate::types::ResolveRiskParams>();

    // ── D2 sales role analysis (T072) ───────────────────────────────────────
    types.register::<crate::types::CounterpartyStance>();
    types.register::<crate::types::CounterpartyTone>();
    types.register::<crate::types::NeedPriority>();
    types.register::<crate::types::NextActionTimeline>();
    types.register::<crate::types::CounterpartyProfile>();
    types.register::<crate::types::NeedItem>();
    types.register::<crate::types::ConcessionAdvice>();
    types.register::<crate::types::NextAction>();
    types.register::<crate::types::ContactHistorySummary>();
    types.register::<crate::types::AnalyzeSalesContextParams>();
    types.register::<crate::types::SalesAnalysisResult>();

    // ── F5 offline fallback (T067) ──────────────────────────────────────────
    types.register::<crate::ai::fallback::SuggestedAction>();
    types.register::<crate::ai::fallback::DowngradeDecision>();
    types.register::<crate::ai::fallback::AiOfflinePayload>();
    types.register::<crate::ai::fallback::AiOnlinePayload>();
    types.register::<crate::ai::fallback::AiRouterStatus>();
    types.register::<crate::ai::fallback::CooldownInfo>();

    // ── Provider config UI surface (T068) ───────────────────────────────────
    types.register::<crate::types::LocalProviderEndpoint>();
    types.register::<crate::types::OllamaModelEntry>();
    types.register::<crate::types::ConfiguredProviderInfo>();

    // ── Recommended provider (T064, F3) ─────────────────────────────────────
    types.register::<crate::ai::recommended::RecommendedTier>();
    types.register::<crate::ai::recommended::RecommendedProviderInfo>();
    types.register::<crate::ai::recommended::BeginRecommendedOAuthResult>();
    types.register::<crate::ai::recommended::CompleteRecommendedOAuthResult>();
    types.register::<crate::ai::recommended::AiSetupStatus>();
    types.register::<crate::ai::recommended::RecommendedOAuthCallback>();

    // ── Data-flow disclosure, AI section (T069) ─────────────────────────────
    types.register::<crate::commands::data_flow::AiEndpointKind>();
    types.register::<crate::commands::data_flow::AiRouteEntry>();
    types.register::<crate::commands::data_flow::AiActivityRow>();
    types.register::<crate::commands::data_flow::DataFlowAiRouting>();

    // ── E5 style learning (T075) ────────────────────────────────────────────
    types.register::<crate::ai::style::StyleProfileJson>();
    types.register::<crate::ai::style::StyleSummary>();
    types.register::<crate::ai::style::StyleProgressPayload>();
    types.register::<crate::ai::style::StyleDonePayload>();
    types.register::<crate::ai::style::StyleErrorPayload>();

    // ── Compose / send (T043) + drafts (T045) ───────────────────────────────
    types.register::<crate::types::Recipient>();
    types.register::<crate::types::SendMailParams>();
    types.register::<crate::types::SendMailResult>();
    types.register::<crate::types::CancelSendResult>();
    types.register::<crate::types::Draft>();
    types.register::<crate::types::SaveDraftParams>();

    // ── Module E — E1 manual reply generation (T077) ────────────────────────
    types.register::<crate::types::AiDraft>();
    types.register::<crate::types::RequestAiReplyParams>();
    types.register::<crate::types::RegenerateDraftParams>();
    types.register::<crate::types::DraftReadyPayload>();

    // ── Module E — E6 draft queue (T080) + approve/cancel send (T090) ───────
    types.register::<crate::types::ListAiDraftsParams>();
    types.register::<crate::types::ApproveDraftResult>();
    types.register::<crate::types::DraftUpdatedPayload>();
    types.register::<crate::types::DraftDiscardedPayload>();

    // ── Module E — E2/E3/E4 pipeline events (T082/T084/T085) ────────────────
    types.register::<crate::types::AutoSentPayload>();
    types.register::<crate::types::AutoLoopDetectedPayload>();
    types.register::<crate::types::PipelineErrorPayload>();
    types.register::<crate::types::RiskAlertPayload>();

    // ── Module I — Agent-IM / TEAM channel (T092) ───────────────────────────
    types.register::<crate::types::ImMessage>();
    types.register::<crate::types::PageResult<crate::types::ImMessage>>();

    // ── Module I — Agent presence (T094) ────────────────────────────────────
    types.register::<crate::types::AgentStatus>();

    // ── Module I — proactive queries (T095/T097) ────────────────────────────
    types.register::<crate::types::PendingQuery>();
    types.register::<crate::types::QueryNewPayload>();
    types.register::<crate::types::QueryExpiredPayload>();

    // ── Module I — structured QA card (T098) ────────────────────────────────
    types.register::<crate::ai::qa_card::QaCardOption>();
    types.register::<crate::ai::qa_card::QaCardSubQuestion>();
    types.register::<crate::ai::qa_card::QaCardResponse>();
    types.register::<crate::ai::qa_card::QaCardContent>();

    // ── Module E — E7 audit log (T088) ──────────────────────────────────────
    types.register::<crate::ai::audit::types::AiDecisionRow>();
    types.register::<crate::ai::audit::types::ListDecisionsParams>();
    types.register::<crate::ai::audit::types::DecisionSummary>();
    types.register::<crate::ai::audit::types::AiDecisionExportFormat>();
    types.register::<crate::ai::audit::types::ExportAiDecisionsParams>();

    // `Language::export` walks the whole map (registered types plus everything
    // they reference), errors on duplicate type names, and emits each named
    // type exactly once in a deterministic (SpectaID) order. Timestamps are
    // i64 on the Rust side, so BigInt must map to `number` (02 §2 wire shape).
    let conf = Typescript::default()
        .header(HEADER)
        .remove_default_header()
        .bigint(BigIntExportBehavior::Number);
    let body = conf
        .export(types.map)
        .map_err(|e| anyhow::anyhow!("specta typescript export failed: {e}"))?;

    // Resolve relative paths against this crate's manifest dir (`src-tauri/`),
    // not the process cwd: `pnpm gen:types` runs `cargo run --manifest-path …`
    // from the repo root, which does NOT change the working directory.
    let out = std::path::Path::new(out_path);
    let out = if out.is_absolute() {
        out.to_path_buf()
    } else {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(out)
    };

    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&out, format!("{body}{PROVISIONAL_APPENDIX}"))?;
    Ok(())
}
